### ISSUE TITLE
ssr plus+ 魔改版gfw模式，谷歌无法访问

### ISSUE THREAD

**Issue by catwithme** [Ameykyl/openwrt18.06_update#5]
gfw模式下，国外红叉，但fb、y2b等其他国外网站可正常访问，唯独谷歌不行；
1、在白名单和全局模式，一切正常；
2、gfw模式，切换不同dns方案，问题没有解决；
3、gfw模式，分别测试不同ssr和v2节点，问题依旧；
4、之前用的v301就有上述问题，全新刷v303还是这个问题；
5、系统日志：（不知道是不是跟这个有关）user.err e2guardian[3655]: Proxy not responding - still waiting after 39001 seconds

实在不知道怎么办了，反馈一下，求指导

**Comment by LYCX2015** [comment]
去广告不要开，有冲突 @catwithme

**Comment by Ameykyl** [comment]
> gfw模式下，國外紅叉，但fb，y2b等其他國外網站可正常訪問，唯獨谷歌不行；
> 1，在白名單和分段模式，一切正常；
> 2，gfw模式，切換不同的dns方案，問題沒有解決；；
> 3，gfw模式，分別測試不同的ssr和v2解碼器，問題依舊；
> 4，之前用的v301有上述問題，全新刷v303還是這個問題；
> 5，系統日誌：（不知道是不是跟這個有關）user .err e2guardian [3655]：代理未響應-39001秒後仍在等待
> 
> 實在不知道怎麼辦了，反饋一下，求指導

更换DNS解析方式

**Comment by catwithme** [comment]
感谢两位大神回复
关闭KoolProxyR plus+，问题解决了。非常感谢LYCX2015
